### ISSUE TITLE
JPQL 쿼리 이슈

### ISSUE THREAD

**Issue by KHS96** [Spharos-StarbucksWebCloneProject-Team5/Backend#52]
### 개요
JPQL- nativeQuery를사용하여서 update쿼리를 실행할 때 에러가 발생.

### 생각해봐야 할 부분
에러 내용 참조해서 해결방안을 찾아봐야겠다.

**Comment by KHS96** [comment]
repository 인터페이스에 @Modifying 과 @Transactional 어노테이션 붙이기

**Comment by jinyeong-afk** [comment]
Good!
